server:
  port: 9193
spring:
  datasource:
    url: jdbc:mysql://localhost:4000/NotificationManagementDB
    username: root
    password: ${DB_PASSWORD}  # Update this with your actual database password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates schema; use 'validate' or 'none' in production
    show-sql: true     # Helps debug database queries?

external-services:
  user-management:
    url: http://localhost:9191
  collaboration:
    url: http://localhost:9195
  consent:
    url: http://localhost:9202

cors:
  allowed-origins: http://localhost:3000,http://localhost:9202
